services:
  frontend:
    build:
      context: ./frontend
    restart: always
    container_name: "broadroom_manager-frontend"
    ports:
      - "80:80"
    working_dir: /app
    volumes:
      - ./frontend:/app
    depends_on:
      backend:
        condition: service_started
    networks:
      - broadroom_manager

  backend:
    build:
      context: ./backend
    restart: always
    container_name: "broadroom_manager-backend"
    ports:
      - "5000:4000"
    networks:
      - broadroom_manager
    
networks:
  broadroom_manager:
    driver: bridge