# Generated by Django 5.0.6 on 2024-05-18 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadrooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadroom',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
