# Generated by Django 5.0.6 on 2024-05-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadrooms', '0002_alter_broadroom_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadroom',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='broadroom',
            name='name',
            field=models.TextField(default='Room One', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='broadroom',
            name='broadroom_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
