# Generated by Django 5.0.6 on 2024-05-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadrooms', '0003_broadroom_description_broadroom_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadroom',
            name='name',
            field=models.TextField(max_length=30, unique=True),
        ),
    ]
