# Generated by Django 5.0 on 2024-05-19 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadrooms', '0004_alter_broadroom_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadroom',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
