# Generated by Django 5.0 on 2024-05-19 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadrooms', '0005_alter_broadroom_name'),
        ('reservations', '0001_initial'),
        ('users', '0002_alter_user_active_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='broadrooms_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='broadroom_id', to='users.user'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='users_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_id', to='broadrooms.broadroom'),
        ),
    ]
