# Generated by Django 5.0 on 2024-05-20 16:47

import django.db.models.deletion
import services.time_counter
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('broadrooms', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now=True)),
                ('finish_time', models.DateTimeField(default=services.time_counter.set_max_time)),
                ('active', models.BooleanField(default=True)),
                ('broadrooms_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='broadrooms.broadroom')),
                ('users_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
