# Generated by Django 5.0 on 2024-05-21 06:42

import services.time_counter
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='finish_time',
            field=models.TimeField(default=services.time_counter.set_max_time),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
