# Generated by Django 5.0.6 on 2024-12-27 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='finish_time',
            field=models.DateTimeField(),
        ),
    ]
