# Generated by Django 5.0.6 on 2024-05-24 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('enrollment', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=70)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
